import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className} style={{ overflow: "hidden" }}>
        <main
          className="text-slate-900 dark:text-slate-100 bg-white dark:bg-slate-900 grid h-screen min-w-full"
          style={{ gridTemplateColumns: "1fr 4fr" }}
        >
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
